# Generated by Django 5.0 on 2024-01-11 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('category', models.CharField(choices=[('collection', 'Collection'), ('monthly_games', 'Monthly Games'), ('coming_monthly_games', 'Coming Monthly Games'), ('coming_soon', 'Coming Soon')])),
                ('name', models.CharField(max_length=50)),
                ('release', models.DateField()),
                ('expiration', models.DateField(blank=True, null=True)),
                ('russian_audio', models.BooleanField()),
                ('russian_subtitles', models.BooleanField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('genre', models.ManyToManyField(blank=True, to='games.genre')),
                ('platform', models.ManyToManyField(blank=True, to='games.platform')),
            ],
        ),
    ]
